package processing.test.erica_map_android;

/* autogenerated by Processing revision 1286 on 2022-11-27 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ERICA_MAP_android extends PApplet {

PImage map;

int mapX = -200;

 public void setup() {
  /* size commented out by preprocessor */;
  /* smooth commented out by preprocessor */;
  
  map = loadImage("map.png");
}

 public void draw() {
  image(map, -5, -5);
}


  public void settings() { size(400, 400);
smooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ERICA_MAP_android" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
